Traceback (most recent call last):
  File "/home/ryan/.conda/envs/work/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/ryan/.conda/envs/work/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/ryan/.conda/envs/work/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/ryan/.conda/envs/work/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/ryan/.conda/envs/work/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/ryan/.conda/envs/work/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/home/ryan/.conda/envs/work/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/ryan/.conda/envs/work/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
for dtheta0 in [1, 2, 3, 4, 5]:
    Z = np.array([[1, 1], 
                  [np.sqrt(g/L), -np.sqrt(g/L)]])
    x0 = np.array([-1.2, dtheta0])

    AB = np.linalg.solve(Z, x0)

    L = 0.8 #m
    g = 9.81 # m/s/s
    e = 2.71828
    t = np.linspace(0, 0.7) #4*np.pi) # 2 time periods of motion
    theta = AB[0]*np.exp(3.5*t) + AB[1]*np.exp(-3.5*t)
    dtheta = np.sqrt(g/L)*(AB[0]*np.exp(3.5*t) - AB[1]*np.exp(-3.5*t))
    ddtheta = g/L*(theta)

    plt.plot(t, theta*180/np.pi)
plt.title('angle in degrees')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-2-308f7f3fb6e2>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;32mfor[0m [0mdtheta0[0m [0;32min[0m [0;34m[[0m[0;36m1[0m[0;34m,[0m [0;36m2[0m[0;34m,[0m [0;36m3[0m[0;34m,[0m [0;36m4[0m[0;34m,[0m [0;36m5[0m[0;34m][0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m     Z = np.array([[1, 1], 
[0;32m----> 3[0;31m                   [np.sqrt(g/L), -np.sqrt(g/L)]])
[0m[1;32m      4[0m     [0mx0[0m [0;34m=[0m [0mnp[0m[0;34m.[0m[0marray[0m[0;34m([0m[0;34m[[0m[0;34m-[0m[0;36m1.2[0m[0;34m,[0m [0mdtheta0[0m[0;34m][0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0;34m[0m[0m

[0;31mNameError[0m: name 'g' is not defined
NameError: name 'g' is not defined

