Traceback (most recent call last):
  File "/home/ryan/.conda/envs/work3-9/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/ryan/.conda/envs/work3-9/lib/python3.9/site-packages/nbclient/client.py", line 1093, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/ryan/.conda/envs/work3-9/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/ryan/.conda/envs/work3-9/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/ryan/.conda/envs/work3-9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/ryan/.conda/envs/work3-9/lib/python3.9/site-packages/nbclient/client.py", line 559, in async_execute
    await self.async_execute_cell(
  File "/home/ryan/.conda/envs/work3-9/lib/python3.9/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/ryan/.conda/envs/work3-9/lib/python3.9/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
reader = imageio.get_reader('https://go.gwu.edu/engcomp3vidmit', format='mp4')
image = reader.get_data(1100)

plt.imshow(image, interpolation='nearest');
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-7-a3d12a9c08d7>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mreader[0m [0;34m=[0m [0mimageio[0m[0;34m.[0m[0mget_reader[0m[0;34m([0m[0;34m'https://go.gwu.edu/engcomp3vidmit'[0m[0;34m,[0m [0mformat[0m[0;34m=[0m[0;34m'mp4'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0mimage[0m [0;34m=[0m [0mreader[0m[0;34m.[0m[0mget_data[0m[0;34m([0m[0;36m1100[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0;34m[0m[0m
[1;32m      4[0m [0mplt[0m[0;34m.[0m[0mimshow[0m[0;34m([0m[0mimage[0m[0;34m,[0m [0minterpolation[0m[0;34m=[0m[0;34m'nearest'[0m[0;34m)[0m[0;34m;[0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'imageio' is not defined
NameError: name 'imageio' is not defined

